- Remove socket file on startup is fail2ban crashed. Thanks to Detlef Reichelt.
git-svn-id: https://fail2ban.svn.sourceforge.net/svnroot/fail2ban/branches/FAIL2BAN-0_8@718 a942ae1a-1317-0410-a47c-b1dcaea8d605

diff --git a/files/suse-initd b/files/suse-initd
--- a/files/suse-initd
+++ b/files/suse-initd
@@ -35,6 +35,13 @@ rc_reset
 case "$1" in
     start)
         echo -n "Starting Fail2Ban "
+        # a cleanup workaround, since /etc/init.d/boot.local removes only. 
+        # regular files, and not sockets 
+        if test -e $FAIL2BAN_SOCKET; then
+            if ! lsof -n $FAIL2BAN_SOCKET &>/dev/null; then
+                rm $FAIL2BAN_SOCKET
+            fi
+        fi
         /sbin/startproc $FAIL2BAN_BIN start &>/dev/null
         rc_status -v
         ;;
