try to use pip-modules asyncore/asynchat

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,7 @@ jobs:
     runs-on: ubuntu-20.04
     strategy:
       matrix:
-        python-version: [3.6, 3.7, 3.8, 3.9, '3.10', '3.11', pypy3.10]
+        python-version: [3.6, 3.7, 3.8, 3.9, '3.10', '3.11', '3.12', pypy3.10]
       fail-fast: false
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -59,6 +59,9 @@ jobs:
           python -m pip install systemd-python || echo 'systemd not available'
           #readline if available as module:
           python -c 'import readline' 2> /dev/null || python -m pip install readline || echo 'readline not available'
+          # asyncore/asynchat:
+          if [[ "$F2B_PYV" = 3.12 ]]; then python -m pip install pyasynchat || echo "can't install pyasynchat"; fi
+          if [[ "$F2B_PYV" = 3.12 ]]; then python -m pip install pyasyncore || echo "can't install pyasyncore"; fi
 
       - name: Before scripts
         run: |
