py3.12: install setuptools (packaged now)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -61,6 +61,8 @@ jobs:
           python -c 'import readline' 2> /dev/null || python -m pip install readline || echo 'readline not available'
           # asyncore/asynchat:
           if dpkg --compare-versions "$F2B_PYV" ge 3.12; then
+            #sudo apt-get -y install python${F2B_PY/2/}-setuptools || echo 'setuptools not unavailable'
+            python -m pip install setuptools || echo "can't install setuptools"
             python -m pip install pyasynchat || echo "can't install pyasynchat";
             python -m pip install pyasyncore || echo "can't install pyasyncore";
           fi
